Fixes #58
spritsail/fivem pull request #59
Opened 2022-12-07 23:16 UTC by nerdfoundrygaming

Added quick notation of how to volume mount for txAdmin data.

2022-12-08 07:32 UTC, frebib approved these changes

2022-12-08 20:47 UTC, Adam-Ant requested changes
Many thanks for putting this together - txAdmin documentation has definitely been lacking! A few small changes & additions needed then I'll be happy to merge this.

2022-12-08 20:47 UTC, Adam-Ant commented on README.md
> +`txAdmin` stores it's configuration and database data in `/txAdmin`, so a volume can be set up to persist this data:
The path here doesn't match the compose file below - it should be `/txData` I think?

2022-12-08 20:47 UTC, Adam-Ant commented on README.md
> +  -p 30120:30120/udp \
Port for txAdmin should be added here

2022-12-08 20:47 UTC, Adam-Ant commented on docker-compose.yml
> +      - "/path/to/txData/folder:/txData"
As this compose file needs to cover all use cases, a comment explaining this is only for txAdmin would be good

2022-12-08 20:47 UTC, Adam-Ant commented on docker-compose.yml
>        - "30120:30120/udp"
Again - port for txAdmin & note explaining its for txAdmin

2022-12-09 07:22 UTC, CodexHere commented
Updated with your requests

2022-12-09 10:47 UTC, Adam-Ant approved these changes
All looks good - many thanks for those changes and your PR!

2022-12-09 10:47 UTC, merged